name: Integration
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

       # Install EKSCTL
       - name: installing eksctl
         run: |
             # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
             ARCH=amd64
             PLATFORM=$(uname -s)_$ARCH
         
             curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
         
             # (Optional) Verify checksum
             curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
         
             tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
         
             sudo mv /tmp/eksctl /usr/local/bin 

       - name: Install kubectl
         uses: azure/setup-kubectl@v3
         with:
            version: 'v1.24.0' # default is latest stable
         id: install

       - name: "Logs into docker"
         uses: docker/login-action@v3
         with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: "Build our Code"
         env:
            IMAGE_NAME: simplepersonal101
            VERSION: latest
            USERNAME: epauldike
         run: |
             docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
             docker push $USERNAME/$IMAGE_NAME:$VERSION
          
       - name: Update kube-config
         run: aws eks update-kubeconfig --name simple
          
      #  - name: Helm install
      #    uses: Azure/k8s-deploy@v4
      #    with:
      #     images: 'epauldike/simplepersonal101:latest'
      #     # imagepullsecrets: |
      #     #    image-pull-secret1
      #     #    image-pull-secret2
      #     manifests: |
      #        simple.yaml

       - name: Deploy to EKS
         run: |
             kubectl apply -f simple.yaml

