name: Integration
on:
  push:
    branches:
       - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
       - name: preparation
         run: echo "preparing to deploy ..."

       - name: check out the repository
         uses: actions/checkout@v4
       
       - name: Make HTTP request
         uses: fjogeleit/http-request-action@v1
         with: 
             url: 'http://api.exchangeratesapi.io/v1/latest?access_key=${{ secrets.API_KEY }}&symbols = USD,AUD,CAD,PLN,MXN'
             method: GET
             customHeaders: '{"content-type": "application/json"}'

       - name: "Logs into docker"
         uses: docker/login-action@v3
         with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: "Build our Code"
         env:
            IMAGE_NAME: simplepersonal101
            VERSION: latest
            USERNAME: epauldike
         run: |
             docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
             docker push $USERNAME/$IMAGE_NAME:$VERSION

